### ISSUE TITLE
64位元

### ISSUE THREAD

**Issue by qpaozixu** [ZeusYang/FluidEngine#1]

**Comment by qpaozixu** [comment]
感謝教學，最近在看流體模擬方面論文，很實用，不過在跑程式時遇到一些小問題，想請問是哪邊設定有誤。 謝謝!
FluidEngine.lib 有錯誤
[
![image](https://user-images.githubusercontent.com/45990118/117305734-9f4cff80-aeb1-11eb-8313-034090974507.png)
](url)

**Comment by ZeusYang** [comment]
> 感謝教學，最近在看流體模擬方面論文，很實用，不過在跑程式時遇到一些小問題，想請問是哪邊設定有誤。 謝謝!
> FluidEngine.lib 有錯誤
> [ ![image](https://user-images.githubusercontent.com/45990118/117305734-9f4cff80-aeb1-11eb-8313-034090974507.png) ](url)

你好，请注意在把在visual studio中把FluidEngine设为启动项目即可。
